### ISSUE TITLE
ListView issue

### ISSUE THREAD

**Issue by boredtodeath** [simple-salesforce/simple-salesforce#123]
Is there a problem with the SF API or it's not even possible to load views?

My view is at https://na26.salesforce.com/500?fcf=00B60000007HzQE
so I am trying with:
result = sf.ListView.get("00B60000007HzQE")
print result

but get
simple_salesforce.api.SalesforceResourceNotFound: Resource ListView Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

**Comment by skamensky** [comment]
@boredtodeath , what API version are you running? The default is 28.0 which does not support ListView as a metadata type. ListView became available in 32.0. I'm running 38.0 and I was able to get `listview.get({Id})` code to work without issue. Try changing the DEFAULT_API_VERSION in api.py to 32.0 or higher. Also note my __init__ is function in the SFType class is using the DEFAULT_API_VERSION instead of the hard coded 28.0. I didn't try running your code with the hard coded 28.0 in place.

**Comment by demianbrecht** [comment]
Closing due to lack of response and @skamensky's suggestion seems like it should resolve the issue. Feel free to reopen if the problem persists!
