### ISSUE TITLE
Not a issue but a question. Is there anyway to create a dynamic soql query

### ISSUE THREAD

**Issue by OtisHarrison24** [simple-salesforce/simple-salesforce#189]
Hi I'm trying to replicate a select * from account in soql but can not figure out how I would do this. Right now I have put each field in but if someone adds a new field or removes it is going to break that query.

thanks

**Comment by digitalaun** [comment]
@OtisHarrison24 SOQL does not support "select *" syntax, so you need to specify the fields explicitly. cf [SOQL select syntax](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select.htm). If you do really need to generate a field list dynamically, you can use the `describe()` method to get the field list and build the SOQL query based on it. e.g. `sf.Account.describe()`

**Comment by OtisHarrison24** [comment]
@digitalaun I tried using the describe field but I it would not loop through the ordered dict I got back? Was trying to pull out fields from the describe.

**Comment by digitalaun** [comment]
The describe results ([sf docs](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_describe.htm)) includes more than just field names, so you'd need to pull them out. If you want to avoid update errors due to field-level permissions, you could also filter out non-updateable fields.
```
desc = sf.Account.describe()
fields = [field['name'] for field in desc['fields']]
```

**Comment by andscoop** [comment]
Question is resolved. Closing out.
