### ISSUE TITLE
Is there a method to send hashed version of password instead of clear text version?

### ISSUE THREAD

**Issue by TheWingineer** [simple-salesforce/simple-salesforce#220]
I'd like my source code to contain the hash of my password instead of the actual password. Is there any way to send the hash instead of the clear text version of my password when logging into SF.com? Currently I'm using the below command with my clear text password.

sf = Salesforce(username=<username>, password=<password>, security_token=<token>)

**Comment by skamensky** [comment]
Not out of the box with simple_salesforce. 

Take a look at how simple_salesforce logs in. It builds XML representing the body of the SOAP request to Salesforce's [login endpoint.](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_quickstart_login.htm) One of the parameters in this XML, required by Salesforce, is the password in plain text.

https://github.com/simple-salesforce/simple-salesforce/blob/364c889abe9e22b7145524f2dc422e41c5f0639b/simple_salesforce/login.py#L67

If you really wanted your password to be hashed in your code you can modify the source code or create a pull request for login.py to accept hashing by allowing the option to decrypt the hash with a given algorithm before it logs in. But depending on how you have your hash stored, that probably won't help too much since your hash will be available in plain text (or available somehow to your program) and so will the decryption algorithm you've chosen to use. So whoever is looking at your code would be able to decrypt it :P.

Did anyone else ever come up with a solution to this?

**Comment by andscoop** [comment]
Ensure that you are only sending your requests over https and pull the credentials from environment variables, ensuring they are never stored in the code itself. I can't think of anything this library can do to help with this problem.
