### ISSUE TITLE
v0.74.0 did not deploy to PyPi

### ISSUE THREAD

**Issue by jlucas91** [simple-salesforce/simple-salesforce#249]
Hey @tedmiston -

It looks like the v0.74.0 merge did not deploy to PyPi. Is there anything I could do to help get that deployed? A new feature in that release would help me cleanup some nastiness in our codebase. 

Thanks!

**Comment by tedmiston** [comment]
Hey @jlucas91, we pulled the build from PyPI because the release from the CI was broken.

I think you could use the release off of GitHub today if you `pip install git+...@v0.74.0`.  If you could try that and let me know if it works for you, that would help us.

The release itself I believe works correctly.  It's just that something strange broken between the CI and PyPI.  PyPI was doing maintenance and a major upgrade around the same time which could be related.  @andscoop and I intend to dive into this soon but we're a bit overloaded at work currently.

Also, see https://github.com/simple-salesforce/simple-salesforce/issues/245.

If you have time and are interested in digging into the CI more, that would be helpful too.

**Comment by andscoop** [comment]
@jlucas91 Thanks for the patience. We have released a new version and deployed to PyPi. Please note the new release is 0.74.1 due to not being able to re-release v0.74.0 due to prohibited filename conflicts on PyPI.
