### ISSUE TITLE
Not a issue more of a question: Have you used simple salesforce in an AWS Lambda

### ISSUE THREAD

**Issue by OtisHarrison24** [simple-salesforce/simple-salesforce#256]
Hi was wondering if you can use simple saleforce in a aws lambda script. Was trying to use the api gateway to pass a customer id to a lambda script and have that lambda script use simple salesforce to grab the customer info?

Thanks in advance for any help

**Comment by tedmiston** [comment]
@OtisHarrison24 I haven't tried this personally but I have used Lambda for other things.  The approach you described sounds like it would work just fine.  If you hit any issues with this setup, just let us know and we can help troubleshoot.

**Comment by OtisHarrison24** [comment]
have trouble with the whole adding simple salesforce to aws. Im using codecommit as my git repo, code build as my unit testing, and codepipeline to do my continuous development. I got codebuild to pip in simple salesforce but it did not push that library up to aws lambda. Should I be zipping it up first and then committing to codecommit?

**Comment by renatoliveira** [comment]
You could always upload your code manually in a zip file too, remembering to install the library in the same folder.

Anyway, did you manage to do this?

**Comment by TalAbramson** [comment]
I am using serverless framework to do the deploy of the function and all its dependencies

**Comment by tedmiston** [comment]
^ I would recommend this approach too.  Another serverless framework you might consider is Zappa.

**Comment by abest0** [comment]
I'm using `simple-salesforce` in a lambda based ETL with results that I'm satisfied with.  Rather than using [serverless](https://serverless.com/) as @TalAbramson & @tedmiston suggested,  I've built the lambda using [sam-local](https://github.com/awslabs/aws-sam-cli) based off of this wonderful [cookiecutter-aws-sam-python template](https://github.com/aws-samples/cookiecutter-aws-sam-python).

The only limitations I've seen thus far are with respect to:
1. making sure you're handling your Salesforce credentials in a secure manner
1. bulk processes that take longer than 5 mins (the max execution time of a lambda function)
1. bulk upserts using `sf.bulk.opportunity.upsert()`

There are fairly comfortable workarounds to each of these limitations:
1. we store Salesforce credentials securely in [aws secrets manager](https://aws.amazon.com/secrets-manager/) and get all the benefits of the service permissioned access, auditing, etc.
1. chunking data processed by the lambda to a reasonable limit
1. we've actually had to use [heroku/salesforce-bulk](https://github.com/heroku/salesforce-bulk) to get around this limitation

Other than that, it's been pretty dreamy.

**Comment by tedmiston** [comment]
^ First time seeing the SAM CLI.  Looks like a pretty cool approach.

**Comment by andscoop** [comment]
@OtisHarrison24 It looks like the above answers have put you on the right path to resolving your question. Please re-open and provide further clarification if these answers do not meet your needs.

**Comment by crawforde** [comment]
Has anyone tried storing Salesforce sessions for us by subsequent Lambda calls? I have an API Gateway service that gets a lot of traffic and we're hitting our Salesforce login limit because we're creating a new session every time the function gets called.

**Comment by shahrakhi** [comment]
Hi. I am trying to use simple_salesforce with AWS glue ETL job. However when I run the job it gives me the following error: "ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'". I have tried various options like manually installing the dependent packages in sequence. But nothing worked. Any help on this will be greatly appreciated. Thank you.

**Comment by jon-wobken** [comment]
Hi,

I have not and don’t have much experience with it. All I have found so far is the knowledge article below.

https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-package-compatible/

**Comment by shahrakhi** [comment]
Thanks @jon-wobken for your help. I will dig into it further.

**Comment by shahrakhi** [comment]
Hello again. 

I was able to make it work using python only library. I am facing another issue with date field in salesforce. I read that we need to pass utc format to salesforce from the API. However, I tried multiple options but none of the format worked. I get an error saying malformed request  while doing an insert operation. My date is in format "YYYY/MM/DD" and i need to convert that is the format accepted by salesforce. I tried the strptime function as mentioned in the documentation but that gives me formatting error. Any help on this will be appreciated!

**Comment by jon-wobken** [comment]
If you are passing straight date instead of date time the accepted format is “YYYY-MM-DD” 

Use the yyyy-MM-ddTHH:mm:ss.SSS+/-HH:mm oryyyy-MM-ddTHH:mm:ss.SSSZ formats to specify dateTime fields.

More info here: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/datafiles_date_format.htm
