### ISSUE TITLE
Need help for Example of uploading a file to a SF Library 

### ISSUE THREAD

**Issue by hiscockj** [simple-salesforce/simple-salesforce#285]
I am a  wanting to use Simple-salesforce to  upload a file to a Salesforce Library.  

I am trying to use sf.contentversion.upsert to upload a file.

Example code:
with open("model1.txt.gz",mode='rb') as f:
        body = base64.b64encode(f.read())
        update_dict = { 'ContentDocumentId' : '691l000000AFSQAA4', 'Title' : 'model1.txt', 'VersionData' : body }
       sf.ContentVersion.upsert(update_dict)

 Getting the message
"Traceback (most recent call last):
  File "./uploadfile.py", line 44, in <module>
    sf.ContentVersion.upsert(update_dict)
TypeError: upsert() missing 1 required positional argument: 'data'"

I might be completely wrong with the function call.  An examples/help would be appreciated

**Comment by cbohlman** [comment]
The upsert function takes two arguments: an Id to match on, and a dict with the data you're creating or updating. You're only passing the dict to the function, which is why you're getting a missing argument error.

See page 18 here for more info (not sure how up to date this is but it should help): https://media.readthedocs.org/pdf/simple-salesforce/latest/simple-salesforce.pdf
