### ISSUE TITLE
bulk upsert without external ID

### ISSUE THREAD

**Issue by aaronamelgar** [simple-salesforce/simple-salesforce#315]
I am able to upsert a single contact using their Salesforce ID as below:
sf.Lead.upsert("XXXXX", {"Field Name" : "Value"}) 

But cannot do the following:
data = [("XXXXX", {"Field Name" : "Value"}), ("XXXXX", {"Field Name" : "Value"})]
bulk.Lead.Upsert(data, 'Lead ID')

In general, why is upsert limited to External IDs?

**Comment by jon-wobken** [comment]
@aaronamelgar - The upsert is not limited to external ids. Your data is formatted incorrectly, please reference the read me but it should be formatted the following for BULK 

```
data = [
      {'Id': '0000000000AAAAA', 'Email': 'examplenew2@example.com'},
      {'Email': 'foo@foo.com'}
    ]

sf.bulk.Contact.upsert(data, 'Id')
```

You also need to define it as "Id" instead of "Lead ID" as this should be API field you are trying to match to and not the label.
