### ISSUE TITLE
Leave payload as JSON and not convert to Ordereddict

### ISSUE THREAD

**Issue by Baelfur** [simple-salesforce/simple-salesforce#319]
I am trying to keep a refreshed fields list from key objects in our instance, and I have no idea how to get this working with an ordereddict. I was going to just use the pandas json_normalize to isolate the fields list, but i can't get it to A) stop converting to ordered dict or B) convert it back to usable json. Is there a way to just get the JSON payload without having it do the conversion to a dict?

**Comment by ScriptingDad** [comment]
Based on the code the `OrderedDict` object is passed as a parameter to `json.load()` so the only real difference between the `OrderedDict` and Dict is that `OrderedDict` doesn't have a nice output but you can otherwise work with it the same as a Dict.  

Just tested it against some sample data and you can de-serialize the response back into json using `json.dumps(response)`.

```python
import json
from collections import OrderedDict
r = sf.query("some query")

json_r = json.dumps(r)                                                                        # now as json
dict_r = json.loads(json_r)                                                                   # now as a normal dict
ordered_dict = json.loads(json_r, object_pairs_hook=OrderedDict)  # this is essential what simple_salesforce is doing.
```

**Comment by thommor** [comment]
Closing, happy to reopen if this is still an issue
