### ISSUE TITLE
`CANNOT_UPDATE_CONVERTED_LEAD` when trying to update a lead

### ISSUE THREAD

**Issue by milind-shakya-sp** [simple-salesforce/simple-salesforce#341]
`simple-salesforce` should ideally have a check to see if a lead, is converted or not, and then only proceed with the update request https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/api.py#L714

This will prevent callers to have to do their own redundant checking all over the place.

**Comment by jon-wobken** [comment]
@milind-shakya-sp - I think this is a bit of a niche use case

1. It would then have to query within the update method to determine if its a converted lead
2. What if a user is attempting to update a lead (which should not have been converted for some reason) they would want that error to be raised. 

Since either way a query call will have to be made to determine if a lead is converted then it should be left up to the author to determine if they want to perform that check, have the error generated, or bypass the error with a try/except.

```
try:
    sf.Lead.update('00Q0v0000067MoiEAE',{'FirstName':'Test1'})
except Exception as e:
    print('exception',e)
    if e.args[3][0].get('errorCode') == 'CANNOT_UPDATE_CONVERTED_LEAD':
        pass
```
