### ISSUE TITLE
Adding concurrency mode as parameter to do serial upload

### ISSUE THREAD

**Issue by yeyeric** [simple-salesforce/simple-salesforce#349]
Hello,

Sometimes we may want for legitimate reasons to do serial upload instead of parallel.
As per this thread this can be done editing the _create_job__ module: https://stackoverflow.com/questions/57960907/python-simple-salesforce-change-concurrencymode

Can this feature be integrated into the project, I think it could be helpful to everyone

thanks

**Comment by jon-wobken** [comment]
Added concurrency mode bulk #345 - pending finishing test cases before merging to master

**Comment by jon-wobken** [comment]
@yeyeric - When needing to do serial uploads, does the order of the batches matter or just that the batches are not processed in parallel?

Example 

```
records = [{'Id':'1'},'Id':'2'},'Id':'3'},'Id':'4'},'Id':'5'},'Id':'6'}]
sf.bulk.sObjectName.update(records),use_serial=1,batchsize=1)

```
This would create 6 batches (each with 1 record) but is not impacted by the order of the list of dicts so technically the batches could look like this

Batch 1) {'Id':'1'}
Batch 2) {'Id':'6'}
Batch 3) {'Id':'3'}
Batch 4) {'Id':'2'}
Batch 5) {'Id':'4'}
Batch 6) {'Id':'5'}

If this does not matter, I believe my I can integrate my solution.

**Comment by yeyeric** [comment]
Hi @jon-wobken , to me this doesn't matter.
Thanks for your solution !

**Comment by sgoley** [comment]
@jon-wobken, I do have a use case for this serial upload where order does matter. 

In my case, an external id field on a custom object was updated with every value offset from the record key by 1 and due to the unique constraint on that field was running into an issue where doing the serial update with the bulk up-loader was still failing. 

Ex. 
` Id = a1a0000...AAY, External_Key__c = null `
` Id = a1a0001...AAY, External_Key__c = uuid_1 `
` Id = a1a0002...AAY, External_Key__c = uuid_2 `
etc. 

Just wondering if your input on this would resolve that case or if, like the standard dataloader - it would only succeed on the update of record 1 and fail the rest of the batch due to duplicate value errors.

**Comment by jon-wobken** [comment]
@sgoley - That is good to know. Currently, my implementation does not take order of the list of dictionary into account since it utilizes multi-threading to uploaded the batches >10k (ex. if you have 50k records, and the list of dictionaries is ordered, the first 10k, records in the dictionary would be batch 1, but any 10k batch after that could be records 20-30k, 300001-40k in any batch 2-5).

I will look to add a sorted method for the upload/delete/upsert/hard_delete/insert to prevent any existing implementations from breaking.

**Comment by jon-wobken** [comment]
@yeyeric @sgoley - Concurrency support added in v1.10 from pull request #392 (use_serial=True)
