### ISSUE TITLE
invalid session id on bulk upload

### ISSUE THREAD

**Issue by nilatti** [simple-salesforce/simple-salesforce#376]
I'm getting an invalid session ID when I try to bulk upload a somewhat complex piece of data to a custom table. For straightforward data to a default table (Contacts) I do not get an error.

```
sf = Salesforce(username='xxxxx', password='xxxxxxx', security_token='xxxxxx', domain='test')
sf.bulk.Contact.upsert(data, 'ak_user_id2__c') #works fine

table2 = { 'item1': {
        'ak_transaction_id__c': '2',
        'contact_r': {'ak_user_id2__c': '7'}, # the one piece of weird data
        'name': 'Recurring 28000817',
        'amount__c': '10.0'
       }}

sf.bulk.donation__c.upsert(table2, 'ak_transaction_id__c') # this fails
```
Salesforce is https://cs54.salesforce.com/ if that matters
The error message is "InvalidSessionId."

I should also note that I'm working on code someone else developed, so I am kind of fumbling around generally

**Comment by jon-wobken** [comment]
@nilatti - It looks like your data structure is incorrect. Table2 should be a list of dicts and you might have a bad field - 'contact_r', if you are attempting to use it as an external id it should be __r. It may be throwing the invalid session id because of the bad field name.

Also are you trying to insert that dictionary into a field? I believe the correct structure should be

```
table2 = [
{  'ak_transaction_id__c': '2',
        'contact_r': {'ak_user_id2__c': '7'}, # the one piece of weird data
        'name': 'Recurring 28000817',
        'amount__c': '10.0'
       }
]
```

**Comment by nilatti** [comment]
Thank you! This was a huge help. Looking the session id sent me down a rabbit trail.
