### ISSUE TITLE
Bulk API 2.0 support

### ISSUE THREAD

**Issue by josuebrunel** [simple-salesforce/simple-salesforce#420]
Hello,
Does `simple-salesforce` supports **bulk API 2.0** ? 
I didn't find anything like that in the code. Does someone has a way to kind of tweak to use the **2.0** version ?

**Comment by jon-wobken** [comment]
At the moment there is no support for bulk api2.0 in simple-salesforce. It would take quite a bit of work to change the existing bulk package to support bulk api 2.0 since it only accepts CSV for the data type. Simple-salesforce currently sends to the bulk module using JSON since Bulk api 1.0 accepts both JSON and CSV data.

**Comment by josuebrunel** [comment]
Thanks @jon-wobken. I hope to have a lil bit of spare time to be able to submit a patch

**Comment by jon-wobken** [comment]
That would be great - would be a great improvement for the future.

**Comment by brno32** [comment]
Is this still unsupported?
