### ISSUE TITLE
AsyncIO support using iaohttp

### ISSUE THREAD

**Issue by zikphil** [simple-salesforce/simple-salesforce#426]
Hello,

I needed the simple-salesforce library to work in async very quickly so I forked the repo and replaced the calls from using requests to aiohttp. Can be viewed here if that interests anybody: [https://github.com/Norwest-Venture-Partners/simple-salesforce-async](https://github.com/Norwest-Venture-Partners/simple-salesforce-async)

Thank you

**Comment by pascaldanek** [comment]
Hello, I am interested by this as well. Is there any plan to make simple-salesforce async anytime soon ? Thx,

**Comment by rjjanuary** [comment]
Thank you! I'm currently using simple-salesforce and needing to support async io for a new project.  Taking a deeper look into this now.

**Comment by jon-wobken** [comment]
@pascaldanek - I currently do not have any plans to make simple-salesforce async as it would be a rather large lift.

**Comment by erewok** [comment]
One suggestion if I may, @jon-wobken, is to add an `aio` package inside simple-salesforce, where http calls can be async. This is what we did in our recent (from this week) fork (although we preferred to use the library `httpx`): https://github.com/MulliganFunding/simple-salesforce/tree/master/simple_salesforce/aio

In this way it's only _adding_ async capabilities and interested users can switch to that without affecting any existing users (assuming they're on a recent python3), but simply importing from `simple_salesforce.aio` instead of the parent package.

We also reimplemented all of the existing tests in this library for the new async modules. We have been using the basic functionality provided by our fork in production in specific apps where we have a good tolerance for beta functionality. Admittedly, these apps are not heavy users of metadata and bulk.

We would be happy to help with upstreaming this work and supporting it after the fact if there's interest.

**Comment by jon-wobken** [comment]
@erewok - wow that’s great. I’ll check it out. I would be surprised if there is a large need to async requests in Metadata or bulk but it’s a nice to have.

I would definitely be interested in that as well as support for the functionality.

**Comment by erewok** [comment]
That's good to know. I can open a pull request as a place to start the discussion? We'd like to extend our test coverage a bit and we would also need to add some information to the docs. There's also the matter of our tests, which are written using `pytest`. I might also recommend publishing async support initially as an alpha or beta release and then inviting users to test it, so we can see if they have issues that have not been uncovered in our own usage of the library. We could talk about this in a new PR if it seems appropriate?

> I would be surprised if there is a large need to async requests in Metadata or bulk but it’s a nice to have.

One potential problem is that if you offer an async API, you have to offer it as async everywhere otherwise you may be inviting people to unwittingly block their event-loop. _Any_ sync call will block _all_ async calls on the event-loop. This is why our fork, for instance, uses `aiofiles` to open the private-key in JWT auth and why we looked at _all_ http-network calls to be reimplemented as async.
