### ISSUE TITLE
Bulk Query Memory Issue

### ISSUE THREAD

**Issue by jjr5330** [simple-salesforce/simple-salesforce#428]
I've been trying to leverage simple-salesforce to retrieve ~50 columns of data that results in ~250K records. I run into Python "Memory Errors" every time I attempt to retrieve this the query output. 

Using the 1st method below seems to retrieve a generator object with all the data, but upon iterating over it the memory error occurs again. Is there anyway to adjust these batches so the generator maybe returns 10K records of which I can then write to to disk during each iteration instead of using RAM which I believe is causing these memory issues?

Your expertise and recommendations on best practices here are much appreciated!

Two query methods have been tried and are outlined below. Both of which produce memory errors.

**1st Method**
create query
query = "SELECT Id, x FROM abc"

**generator on the results page**
fetch_results = sf.bulk.Opportunity.query(query, lazy_operation=True)

**the generator provides the list of results for every call to next()**
all_results = []
for index, list_results in enumerate(fetch_results):
    test = pd.DataFrame(list_results)
    file_path = "test{}.csv".format(index)
    test.to_csv(file_path, index=False)

**2nd Method**
query = sf.query_all("SELECT Id, x FROM abc")

df = pd.DataFrame(query ["records"]).drop(columns="attributes")

**Comment by jon-wobken** [comment]
@jjr5330 - If you use query_all_iter (sf.query_all_iter(query)) it will return the actual generator instead of using the bulk query method. You should be able to then loop through your generator and handle the records as needed instead of calling the dataframe on each batch of results which is what is happening in the sf.bulk query method. You are returning ~10k results x 50 columns wide when you call teh pd.DataFrame.

If you handle it with the below (note: might need some tweaking I just jotted this down)

```
query = sf.query_all_iter("SELECT Id, x FROM abc")

counter = 0
records = []
batch_number = 1000 #Set this to whatever you'd like depending on your memory need/usage
for index, i in enumerate(query):
    records.append(i["records"])
    counter+=1
    if counter >=batch_number
        df = pd.DataFrame(records).drop(columns='attributes')
        df.to_csv("test{}.csv".format(index),index=False)
        
```
Let me know if this handled it for you
