### ISSUE TITLE
Login using OAuth2.0 redirection

### ISSUE THREAD

**Issue by bazarnov** [simple-salesforce/simple-salesforce#472]
Hi, is there any option to login into SalesForce by calling:

```
# Example code
sf = Salesforce(instance_url = "https://my.salesforce.instance.com")  > 
   open the web-page with instance_url >
   promt to login with Username & Password >
   retrieve the login response with access_token stored as list or dictionary object back to Python
```

The logic behind this could be described as follows:
- the simple_salesforce opens the web browser page with instance_url mention above and prompts the user to complete auth procedure using the simple way like everybody does (by entering its Username & Password or using SSO like Gmail)
- the simple_salesforce catches the output from login response and retrieves the access_token value back to Python into SF variable as list or dictionary object for later use

This would potentially bring a lot of headaches for the developer, but this definitely would simplify the login process for those who don't deal or cannot deal with Connected Apps, especially for those who need to obtain backend data, but those users don't have admin permissions.

Maybe this has already been solved within simple_salesforce and I'm making another issue here, however, this is a much easier way to obtain access_token for a user, without needing to know every single "secret" behind the salesforce account scenes.

Thanks for the answer!

**Comment by brno32** [comment]
I don't think simple salesforce has anything for this, because it involves setting up a web server which can receive the callback url and all that. I don't know of you're using django but you could maybe make use of my library

https://github.com/Kicksaw-Consulting/django-salesforce-oauth

Once you have an access token, you can then use `simple-salesforce` with it. No need for security tokens. You can do it like

```python
Salesforce({"instance": <your-instance>, "session_id": <access-token>})
```
