### ISSUE TITLE
Can Upsert Insert?

### ISSUE THREAD

**Issue by edgemarkit** [simple-salesforce/simple-salesforce#529]
Is it just me, or is the Upsert not actually an Upsert?
`method='PATCH', url=urljoin(self.base_url, record_id)`
The PATCH method requires a record_id, but if you are creating a new record, you will not have this information. POST is used to create a record from data without an ID.
It does not seem as though there is any way to actually create a record with the Upsert function. Wouldn't that make it just an Update function then? Or am I missing something?

**Comment by edgemarkit** [comment]
In fact, looking at it again, the code for Upsert and Update are actually both identical. Is this intentional? I've reimplented an inserting Upsert for my own purposes by checking for the record_id and switching the method to POST if it is not provided.

**Comment by jon-wobken** [comment]
Hey @edgemarkit there is no need to check for the record first and waste an API call. The upsert and update method are identical in how Salesforce implements them in their api endpoints. It is mostly just to be explicit on the operation in simple Salesforce as well. 

Here is the api docs for reference https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm

Essentially, if the Record Id is left blank a new record will be created. If you pass a record I’d that does not exist it will throw an error and not create a record. If you utilize the external id field on your upsert (or update) “external_id_field/id_value” then it will update the record if it finds a match on that external id otherwise it will attempt to create the record.
