### ISSUE TITLE
Unable to serialize object Salesforce

### ISSUE THREAD

**Issue by laubzega** [simple-salesforce/simple-salesforce#60]
I need to serialize object Salesforce so that I can store it in Django's request.session for repeated use. However, neither JSON- nor Pickle-based serializers can handle it. I ended up adding following code to `Salesforce.__getattr__()`
```python
        # fix that enables pickle to work
        if name.startswith('__') and name.endswith('__'):
            return super(Salesforce, self).__getattr__(name)
```
to eliminate problems caused by special attributes, but there may be a better solution.

**Comment by nickcatal** [comment]
I really like your fix. Considering Salesforce objects will never start with 2 leading underscores I think changing the library so that mangled attributes are always returned with `super(Salesforce, self).__getattr__(name)` makes perfect sense.

If you can, please do a pull request that has something along the lines of

```python
    if name.startswith('__'):
        return super(Salesforce, self).__getattr__(name)
```

**Comment by demianbrecht** [comment]
Closing as fix was merged.
