### ISSUE TITLE
Unable to add new Custom Field to existing object (custom/standard)?

### ISSUE THREAD

**Issue by janb-frontify** [simple-salesforce/simple-salesforce#602]
When trying to UPDATE CustomObject with newly added custom field, I get this error message:
`TestCustomObject__c.AccountNumber_NEW__c: (INVALID_CROSS_REFERENCE_KEY, In field: fullName - no CustomField named TestCustomObject__c.AccountNumber_NEW__c found)`

My code looks like this:
```
custom_object = mdapi.CustomObject.read(custom_object_fullname)
custom_field = mdapi.CustomField(
                        fullName="AccountNumber_NEW__c", description="Not used"
                    )
                    new_fields = [custom_field]
custom_object.fields += new_fields
mdapi.CustomObject.update(custom_object)
```
Any idea, what I'm doing wrong here? Thanks.

**Comment by hkajiwara** [comment]
The `update()` API is to update the exiting field on the object and _INVALID_CROSS_REFERENCE_KEY_ is thrown when it's not existing. If it's newly added, you would need to use `upsert()` API which is a wrapper of [upsertMetadata()](https://developer.salesforce.com/docs/atlas.en-us.240.0.api_meta.meta/api_meta/meta_upsertMetadata.htm).

```
mdapi.CustomObject.upsert(custom_object)
```

Unfortunately it looks there is a bug on the current `upsert()` [function](https://github.com/simple-salesforce/simple-salesforce/blob/master/simple_salesforce/metadata.py#L135) as it wrongly calls `updateMetadata()` instead of `upsertMetadata()`. The fix is straightforward to just replace `updateMetadata()` with `upsertMetadata()`. I'll submit a PR later.

**Comment by janb-frontify** [comment]
Thanks, `upsertMetadata()` works fine.
